name: Submit Blog Post

on:
  workflow_dispatch:
    inputs:
      authToken:
        description: 'Password or token'
        required: true
      blogTitle:
        description: 'Blog title'
        required: true
      blogContent:
        description: 'Blog body text'
        required: true

permissions:
  contents: write

jobs:
  blog-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate token
        run: |
          if [[ "${{ inputs.authToken }}" != "${{ secrets.AUTHORIZED_TOKEN }}" ]]; then
            echo "Invalid token."
            exit 1
          fi

      - name: Convert blog to HTML and save to file
        run: |
          safeTitle=$(echo "${{ inputs.blogTitle }}" | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
          filePath="blogs/${safeTitle}.html"

          mkdir -p blogs
          echo "<html><head><title>${{ inputs.blogTitle }}</title></head><body>" > "$filePath"
          echo "<h1>${{ inputs.blogTitle }}</h1>" >> "$filePath"
          echo "<p>${{ inputs.blogContent }}" | sed 's/$/<\/p>/' >> "$filePath"
          echo "</body></html>" >> "$filePath"

          echo "Blog saved to $filePath"

      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blogs/*.html
          git commit -m "Add blog: ${{ inputs.blogTitle }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
